version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6400:6400
  
  server-express:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - '3000:3000'
    depends_on:
      - redis